name: ServerInfo
main: com.smallaswater.serverinfo.ServerInfoMainClass
version: 1.0.10-SNAPSHOT
api: 1.0.11
load: POSTWORLD
softdepend:
  - "MemoriesOfTime-GameCore"

commands:
  trs:
    description: 显示跨服服务器GUI
    usage: "/trs 打开GUI界面(游戏内)"
